# Numpy

In [3]:
#Python Numpy

In [6]:
#importing python NumPy library
import numpy as np

In [7]:
l1=[1,2,3,4]

In [8]:
#converting list into numpy array
n1=np.array(l1)

In [9]:
n1

array([1, 2, 3, 4])

In [10]:
type(n1)

numpy.ndarray

In [8]:
#creating Numpy multidimensional array
n2=np.array([[1,2,3,4],[4,3,2,1]])

In [15]:
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [16]:
type(n2)

numpy.ndarray

In [17]:
# 2.initializing NumPy array with zeros

In [19]:
n3=np.zeros((2,3))

In [20]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
n3=np.zeros((5,5))

In [22]:
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
# 3. Initializing NumPy array with same numbers.

In [26]:
n4=np.full((3,3),10)

In [27]:
n4

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [1]:
# 4. initializing NumPy array within a range

In [3]:
import numpy as np
n1= np.arange(50,100)

In [4]:
n1

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
#initializing NumPy array within a range with gap

In [6]:
n2 = np.arange(10,100,10)

In [7]:
n2

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
# 5. Initializing NumPy array with random numbers 

In [11]:
np.random.randint(100,200,10)

array([155, 151, 138, 176, 102, 116, 176, 169, 147, 117])

In [12]:
np.random.randint(100,200,10)

array([155, 126, 152, 130, 134, 143, 161, 126, 166, 159])

In [1]:
# 6. Cheking the shape of NumPy array 

In [2]:
import numpy as np

In [3]:
n1 = np.array([[1,2,3,4],[4,3,2,1]])

In [4]:
n1

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [6]:
#checking shape of n1
n1.shape

(2, 4)

In [8]:
# changing shape of NumPy array
n1.shape = (4,2)

In [9]:
n1

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [10]:
n1.shape

(4, 2)

In [19]:
#modifying NumPy array
# Create a 5 * 2 Matrix with all zeros
np_arr = np.zeros((5,2))

In [20]:
np_arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
# Put 1 to the 5 * 2 Matrix
np.put(np_arr, range(10), np.ones((5,2)))

In [22]:
np_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
np.put(np_arr, range(10), [1,2,3,4,5,6,7,8,9,0])

In [18]:
np_arr

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [24]:
# 7. Joining NumPy array

In [25]:
n1 = [1,2,3]

In [26]:
n2 = [4,5,6]

In [29]:
#vertical stack
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# horizontal stack
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [32]:
# column stack
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [1]:
# 8. Union, Intersection and difference operation on NumPy arrays

In [2]:
import numpy as np

In [3]:
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])

In [5]:
#NumPy union
np.union1d(n1,n2)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
# NumPy Intersection
np.intersect1d(n1,n2)

array([50, 60])

In [9]:
# NumPy difference in n1
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [10]:
# NumPy difference in n2
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [12]:
#9.  NumPy array Mathematics

In [14]:
#Addition of NumPy arrays 

In [15]:
n1 = np.array([10,20])
n2 = np.array([30,40])

In [16]:
np.sum([n1,n2])

100

In [23]:
# adding elements of column
np.sum([n1,n2],axis=0)

array([40, 60])

In [24]:
#adding elements of row
np.sum([n1,n2],axis=1)

array([30, 70])

In [1]:
# 10. Performing Operations with scalar values on NumPy array

In [2]:
import numpy as np

In [3]:
n1 = np.array([10,20,30])

In [4]:
#Addtion with scalar value on NumPy array
n1+5

array([15, 25, 35])

In [5]:
#Substraction with scalar value on NumPy array
n1-5

array([ 5, 15, 25])

In [6]:
#Multiplication with scalar value on NumPy array
n1*10

array([100, 200, 300])

In [7]:
#Division with scalar value on NumPy array
n1/2

array([ 5., 10., 15.])

In [8]:
# 11. NumPy Math Functions

In [9]:
n1 = np.random.randint(1,50,10)

In [10]:
n1

array([ 9,  6,  3, 47, 48, 40, 23,  5,  1, 32])

In [11]:
#mean 
np.mean(n1)

21.4

In [12]:
#median
np.median(n1)

16.0

In [13]:
np.mode(n1)

AttributeError: module 'numpy' has no attribute 'mode'

In [14]:
# there are two more methods left: mode and standard deviation
# I leave it beacause it's the part of statistics.

In [15]:
#12. NumPy Save and Load

In [16]:
n1 = np.array([10,20,30,40,50])

In [17]:
n1

array([10, 20, 30, 40, 50])

In [18]:
#saving NumPy array
np.save('my_array',n1)

In [20]:
#loading saved NumPy array
new_n1=np.load('my_array.npy')

In [21]:
new_n1

array([10, 20, 30, 40, 50])